version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:9.6
    volumes:
      # volume dos dados
      - dados:/var/lib/postgresql/data 
      # scripts
      - ./scripts:/scripts 
      # convenção padrão da imagem do postgres > após inicializar o banco irá executar todos os scripts ".sql" e ".sh" que estiverem neste diretório
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql 
  frontend:
    image: nginx:1.13
    volumes:
      # arquivos do site
      - ./web:/usr/share/nginx/html/
    ports:
      - 80:80