version: '2.4'

services:
  ts:
    build:
      context: .
      target: dev # Define o estágio do Dockerfile multistage
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/app
